# Generated by Django 5.1.3 on 2024-12-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_is_employee_alter_profile_user_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_rights',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('worker', 'Worker')], default='user', max_length=10),
        ),
    ]
