# Generated by Django 5.1.3 on 2024-12-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_user_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handler_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_tickets', to='myapp.profile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to='myapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('new', 'New'), ('in_prog', 'In Progress '), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replaced_at', models.DateTimeField(null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='myapp.ticket')),
            ],
        ),
    ]
